name: First Workflow
on: [push, workflow_dispatch]
jobs:
  testing_code:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: dependency-${{ hashFiles('**/package-lock.json')}}        
      - name: Install dependencies
        run: npm ci
      - name: Run Linting
        run: npm run lint 
      - name: Test code
        run: npm run test          
        
  building_code:
    needs: testing_code  
    runs-on: ubuntu-latest
    outputs: 
      script-file:  ${{steps.publish.outputs.script-file}}
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: dependency-${{ hashFiles('**/package-lock.json')}}        
      - name: Install dependencies
        run: npm ci        
      - name: Test code
        run: npm run test      
      - name: build code
        run: npm run build
      - name: Publish JS file
        id: publish
        run: find dist/assets/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'        
      - name: Upload artifacts 
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist

          
  deploying_code:
    needs: building_code
    runs-on: ubuntu-latest
    steps:
      - name: Get Build artifacts 
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: dist
      - name: Output filename
        run: echo "${{needs.building_code.outputs.script-file}}"          
      - name: Deploy
        run: echo "Deploying..."            
