name: First Workflow

on: [push, workflow_dispatch]

jobs:
  first_job:

    runs-on: ubuntu-linux
  
    steps:
      - name: Get code
        uses: actions/checkout@v4 

      - name: Run lint
        run: echo "anc"

  second_job:

    runs-on: ubuntu-linux
  
    steps:
      - name: Get code
        uses: actions/checkout@v4 

      - name: Run Test
        run: echo Hello, world! 

  third_job:

    runs-on: ubuntu-linux
  
    steps:
      - name: Build
        uses: actions/checkout@v4 

      - name: Run a one-line script
        run: echo Hello, world!         